[workspace]
resolver = "2"
members = [
    "crates/lush-syntax",
    "crates/lush-types",
    "crates/lush-ir",
    "crates/lush-vm",
    "crates/lush-test-support",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Mdalasini/lush"

[workspace.dependencies]
ariadne = "0.5"
insta = "1.42"
lush-syntax = { path = "crates/lush-syntax" }
lush-test-support = { path = "crates/lush-test-support" }
