[workspace]
resolver = "2"
members = ["crates/lush-syntax", "crates/lush-types"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Mdalasini/lush"

[workspace.dependencies]
logos = "0.14"
thiserror = "2"
insta = "1"
lush-syntax = { path = "crates/lush-syntax" }
